### ISSUE TITLE
Add FEATURE : Dark Mode

### ISSUE THREAD

**Issue by venukotamraju** [gits-up/temp-conversion#10]
Hey thanks for this project. I am fairly new to open source and was wondering where to start. I would like to add dark mode to the UI. Can you assign me the task?

**Comment by gits-up** [comment]
Well someone already asked for it but since they didnt ask here i will also give you that

**Comment by gits-up** [comment]
So there is someone who gave a purple color to the light mode page after going to dark mode from there and coming back to light mode the page color gets white instead of purple....can you look into it?

**Comment by venukotamraju** [comment]
Sure! - PATCHED IT UP!!!    I just have another query. My profile in hackoctober fest page is still viewing my contributions as 0 and the following is being shown. Can you help me with it...:)
![image](https://github.com/gits-up/temp-conversion/assets/77572057/e0bd60f8-f39b-4bf6-ab8f-a78d9f19d09a)
![image](https://github.com/gits-up/temp-conversion/assets/77572057/b4f83d84-dbb5-411c-a28c-b8c5fac838b4)

**Comment by gits-up** [comment]
it should be good to go now

**Comment by venukotamraju** [comment]
Yes it's been updated. Thank you @gits-up :)

**Comment by venukotamraju** [comment]
Cheers🎉
